//script generated by SiteXpert (www.xtreeme.com/sitexpert/)
//Copyright(C) 1998-2003 Xtreeme GmbH
function zz(e,i){
return e?e.document.getElementById(i):document.getElementById(i)}
function f33(p){
if(p&&p.indexOf(':/')==-1&&p.indexOf(':\\')==-1&&p.indexOf('/')!=0) return unescape(absPath)+p
else return p}
function addLoadHandler(lh){
if(!document.loadHandlers){
document.loadHandlers=new Array()
document.loadHandlers[0]=lh
document.lastLoadHandler=0}
else{
document.lastLoadHandler++
document.loadHandlers[document.lastLoadHandler]=lh}}
addLoadHandler('f29')
window.onload=f31
function f32(){return true;}
window.onerror=f32
function f03(q,popup,id,v27,v26,v30,v09,bLast,v31,parent){
var itemType=0
if(v26&&v26.indexOf("(^1)")!=-1)itemType=1
if(v26&&v26.indexOf("(^2)")!=-1)itemType=2
var itemWnd=q.v18.document.createElement("DIV")
popup.appendChild(itemWnd)
if(mac){
var brWnd=q.v18.document.createElement("BR")
popup.appendChild(brWnd)}
f30(itemWnd,"mouseover",f22,false)
f30(itemWnd,"mouseout",f23,false)
f30(itemWnd,"mousedown",f20,false)
f30(itemWnd,"dblclick",f20,false)
itemWnd.owner=popup
itemWnd.id=id
with(itemWnd.style){
position="absolute"
if(itemType==2)top=v31-q.scrollHeight
else top=v31
if(v27){cursor=(!IE4||version>=6)?"pointer":"hand";}
else{cursor="default";}
color=v09 [3]
left=q.popupLeftPad+q.vertSpace
if(!itemType)padding=q.vertSpace
paddingLeft=q.popupLeftPad+q.vertSpace
paddingRight=(q.v01<q.iconSize?q.iconSize:q.v01)+q.vertSpace
fontSize=v09[0]
fontWeight=(v09[1])?"bold":"normal"
fontStyle=(v09[2])?"italic":"normal"
fontFamily=v09[6]
textAlign=(q.v22==1?'center':(q.v22==2?'right':'left'))
f04(itemWnd,q.v11?q.v02-q.popupLeftPad-q.v01-2*q.vertSpace:q.v02,2*q.bord)}
if(v30)itemWnd.v30=v30
if(itemType>0){
var arrow=q.v18.document.createElement("IMG")
itemWnd.appendChild(arrow)
var arrowSrc=f33(q.v21)
arrow.src=arrowSrc+"/"+q.fnm+"s"+((itemType==1)?"up":"down")+".gif"
itemWnd.style.textAlign="center"
itemWnd.style.display="none"}
else
itemWnd.innerHTML=v26
itemWnd.url=f33(v27)
itemWnd.dispText=v26
if(v30){
var expandArrow=q.v18.document.createElement("IMG")
itemWnd.appendChild(expandArrow)
var v03=f33(q.v21)
expandArrow.src=v03+"/"+q.fnm+"ia.gif"
with(expandArrow.style){
width=q.iconSize
height=q.iconSize
position="absolute"
var itemRect=f19(q,itemWnd)
top=(itemRect.bottom-itemRect.top)/2-q.iconSize/2-2
left=itemWnd.offsetWidth-q.iconSize-1}}
return itemWnd.offsetHeight}
function f04(wnd,width,borderWidth){
wnd.style.width=width-borderWidth
if(wnd.offsetWidth>width-borderWidth)wnd.style.width=width-parseInt(wnd.style.paddingLeft)-parseInt(wnd.style.paddingRight)}
function f05(q,v12,level,v04){
var popupName=v12+"popup"
var popup=zz(q.v18,popupName)
if(popup)return popup
var v09
if(level>0)q.v02=q.v23
if(level>q.maxlev){v09=eval("q.lev"+q.maxlev);}else{v09=eval("q.lev"+level);}
popup=q.v18.document.createElement("DIV")
q.v18.document.body.appendChild(popup)
popup.id=popupName
popup.v04=v04
popup.level=level
popup.v05=v09[5]
popup.v06=v09[3]
popup.v07=v09[7]
popup.v08=v09[4]
popup.scrVis=false
with(popup.style){
zIndex=maxZ
position="absolute"
width=q.v02
if(!q.v11){
borderColor=q.borderCol
backgroundColor=v09[4]
borderWidth=q.bord
borderStyle="solid"}
else backgroundColor=""}
popup.q=q
f30(popup,"mouseout",f15,false)
f30(popup,"mouseover",f14,false)
var v31=0
if(q.v11){
var source=zz(0,q.name+'menubg4')
if(source){
var imel=q.v18.document.createElement("IMG")
popup.appendChild(imel)
imel.src=source.src
imel.id=popup.id+"openingImg"
imel.style.position="absolute"
imel.style.top=0
v31+=q.v10}}
var bgWnd=q.v18.document.createElement("DIV")
popup.appendChild(bgWnd)
bgWnd.id=popup.id+"bgWnd"
bgWnd.style.position="absolute"
bgWnd.style.top=q.v10
bgWnd.style.width=q.v02-2*q.bord
bgWnd.innerHTML="<font size='1'>&nbsp;</font>"
if(q.v11){
var source=zz(0,q.name+'menubg5')
if(source)bgWnd.style.backgroundImage="url("+source.src+")"}
var array=eval(v12)
var v13
f03(q,popup,popup.id+"scrollUp","javascript:scrollUp("+q.name+",'"+popup.id+"');","(^1)",null,v09,true,v31,bgWnd)
for(v13=0;v13<array.length/3;v13++){
var v30=(array[v13*3+2])?(v12+"_"+parseInt(v13+1)):null
v31+=f03(q,popup,null,array[v13*3+1],array[v13*3],v30,v09,(v13==array.length/3-1),v31,bgWnd)}
f03(q,popup,popup.id+"scrollDown","javascript:scrollDown("+q.name+",'"+popup.id+"');","(^2)",null,v09,true,v31,bgWnd)
var v28=0
if(q.v11){
var source=zz(0,q.name+'menubg6')
if(source){
var imel=q.v18.document.createElement("IMG")
popup.appendChild(imel)
imel.src=source.src
imel.id=popup.id+"closingImg"
imel.style.position="absolute"
imel.style.top=v31-1
v28=imel.offsetHeight
v31+=v28}}
popup.style.height=v31+q.bord*2+v28
popup.maxHeight=v31+q.bord*2
bgWnd.style.height=v31-q.v10-v28
if(popup.offsetHeight>v31+q.bord*2+v28){popup.style.height=v31;q.bIncBorder=false;popup.maxHeight=v31;}
return popup}
function f06(q,popupId,dl){
if(popupId.indexOf('_')==-1){
var hideWnd=zz(q.v18,'HideItem')
if(hideWnd)hideWnd.style.visibility='visible'
if(q.actm&&dl)chgBg(q,q.actm,0,1)}
if(q.v29){q.v29Str=null;clearTimeout(q.v29);}
var popup=zz(q.v18,popupId)
if(popup){
if(popup.v14)f06(q,popup.v14.id)
if(popup.v04)popup.v04.v14=null
popup.style.visibility="hidden"
popup.style.display="none"}
if(q.v17&&q.v17.id==popupId)q.v17=null}
function f07(rect,refx,refy){
var retval=new rct(rect.left-refx,rect.top-refy,rect.right-refx,rect.bottom-refy)
return retval}
function f34(popup,actEl){
var items=popup.getElementsByTagName("DIV")
var i=0
for(;i<items.length;i++)if(actEl!=items[i]&&(!items[i].id||items[i].id.indexOf("scroll")==-1)){
items[i].style.backgroundColor=popup.q.v11?"transparent":popup.v08
items[i].style.color=popup.v06}}
function f08(q,popup,x,y,bDontMove,refWnd){
if(popup.id.indexOf('_')==-1){var hideWnd=zz(q.v18,'HideItem');if(hideWnd)hideWnd.style.visibility='hidden';}
if(q.v17&&q.v17.id==popup.id)return
popup.style.left=x
popup.style.top=y
popup.style.display=""
popup.style.visibility="visible"
var v15=f19(q,popup)
var v16=f17(q.v18)
var bResize=(popup.offsetHeight<popup.maxHeight)
if(v15.right>v16.right){
if(refWnd&&refWnd.id&&refWnd.id.indexOf('top')==-1)popup.style.left=Math.max(0,refWnd.offsetLeft-popup.offsetWidth+q.levelOffset)
else popup.style.left=v16.right-popup.offsetWidth-5}
var wnd1=zz(q.v18,popup.id+"scrollDown")
var wnd2=zz(q.v18,popup.id+"scrollUp")
var cv=mac?15:(q.bIncBorder?3:20)
if(((v15.bottom>v16.bottom)||bResize)&&!NS60){
var newtop=v16.bottom-popup.offsetHeight-cv
if(!q.menuHorizontal)bDontMove=false
if(newtop<0||bDontMove||bResize){
var minNum=Math.min(popup.maxHeight,v16.bottom-popup.offsetTop-cv-(q.bIncBorder?0:q.bord*2))
popup.scrVis=(minNum!=popup.maxHeight)
f09(q,popup,v16.top,minNum)}
else
popup.style.top=newtop}
wnd1.style.display=popup.scrVis?"":"none"
wnd2.style.display=popup.scrVis?"":"none"
f34(popup,null)}
function f09(q,popup,documentOffset,height){
var wnd2=zz(q.v18,popup.id+"scrollDown")
var wnd4=zz(q.v18,popup.id+"scrollUp")
var wnd3=zz(q.v18,popup.id+"bgWnd")
var wnd1Height=0
if(q.v11){
var wnd1=zz(q.v18,popup.id+"closingImg")
var wnd5=zz(q.v18,popup.id+"openingImg")
wnd1Height=wnd1.offsetHeight
wnd1.style.top=height-1-wnd1Height}
wnd2.style.zIndex=maxZ+1
wnd4.style.zIndex=maxZ+1
popup.style.height=height
wnd3.style.height=height-q.v10-q.bord*2-wnd1Height
wnd2.style.top=height-wnd1Height-q.scrollHeight-(q.bIncBorder?q.bord*2:0)
f10(q,popup.id,0)}
function f10(q,popupId,dir){
var popup=zz(q.v18,popupId)
var v15=f19(q,popup)
var items=popup.getElementsByTagName("DIV")
var i=(dir>0?0:items.length-1)
var off=(dir>0?1:-1)
var bFirst=true
var offset=dir*q.scrollStep
if(popup.scrVis){
v15.top+=q.scrollHeight
v15.bottom-=q.scrollHeight}
v15.bottom-=2*q.bord
var wnd1Height=0
if(q.v11)wnd1Height=zz(q.v18,popup.id+"closingImg").offsetHeight
for(;i<items.length&&i>=0;i+=off){
var item=items[i]
if(!item.id||(item.id.indexOf("scroll")==-1&&item.id.indexOf("bgWnd")==-1)){
var itemRect=f19(q,item)
if(bFirst&&dir==0){offset=popup.maxHeight-(item.offsetTop+item.offsetHeight)+(popup.scrVis?q.scrollHeight:0)-(q.bIncBorder?q.bord*2:0)-wnd1Height;}
var relRect=f07(v15,itemRect.left,itemRect.top+offset)
if(dir>0&&relRect.top<-q.scrollHeight&&bFirst)return
if(dir<0&&itemRect.bottom+offset<v15.bottom-q.scrollHeight-wnd1Height&&bFirst)return
if(offset!=0)item.style.top=item.offsetTop+offset
if(!mac)item.style.clip="rect("+relRect.top+","+relRect.right+","+relRect.bottom+","+relRect.left+")"
if(relRect.bottom<0||relRect.top>item.offsetHeight)
item.style.visibility="hidden"
else
item.style.visibility="visible"
bFirst=false}}
if(popup.scrPos)popup.scrPos+=offset
else popup.scrPos=offset}
function scrollUp(q,popupId){
f10(q,popupId,1)}
function scrollDown(q,popupId){
f10(q,popupId,-1)}
function f13(q,popup){
var wnd=q.v17
while(wnd){
if(wnd.id==popup.id)
return true
wnd=wnd.v14}
return false}
function f14(){
var q=this.q
if(q.v17&&q.v17Timeout&&f13(q,this))clearTimeout(q.v17Timeout)}
function f15(){
var q=this.q
f15Impl(q,this)}
function f15Impl(q,popup){
if(q.mout&&q.v17&&f13(q,popup)){
if(q.v17Timeout)clearTimeout(q.v17Timeout)
q.v17Timeout=setTimeout("f06("+q.name+",'"+q.v17.id+"',1);",q.closeDelay)}}
function rct(left,top,right,bottom){
this.left=left
this.top=top
this.right=right
this.bottom=bottom}
function f17(doc){
var left=0
var top=0
var right
var bottom
if(doc.pageXOffset)left=doc.pageXOffset
else if(doc.document.body.scrollLeft)left=doc.document.body.scrollLeft
if(doc.pageYOffset)top=doc.pageYOffset
else if(doc.document.body.scrollTop)top=doc.document.body.scrollTop
if(doc.innerWidth)right=left+doc.innerWidth
else if(doc.document.body.clientWidth)right=left+doc.document.body.clientWidth
if(doc.innerHeight)bottom=top+doc.innerHeight
else if(doc.document.body.clientHeight)bottom=top+doc.document.body.clientHeight
var retval=new rct(left,top,right,bottom)
return retval}
function f18(q,wnd){
var left=mac?parseInt(document.body.leftMargin):0
var top=mac?parseInt(document.body.topMargin):0
var right=0
var bottom=0
var par=wnd
while(par){
left=left+parseInt(par.offsetLeft)
top=top+parseInt(par.offsetTop)
if(par.offsetParent==par || par.offsetParent==q.v18.document.body)break
par=par.offsetParent}
right=left+parseInt(wnd.offsetWidth)
bottom=top+parseInt(wnd.offsetHeight)
var retval=new rct(left,top,right,bottom)
return retval}
function f19(q,wnd){
if((mac||DOM||Opera7)&&wnd.getBoundingClientRect)return wnd.getBoundingClientRect()
return f18(q,wnd)}
function findFr(wn,fr){
if(wn.frames){
for(var i=0;i<wn.frames.length;i++){
if(wn.frames[i].name==fr)return wn.frames[i]
var ret=findFr(wn.frames[i],fr)
if(ret)return ret}}
return null}
function f20(){
var item=this
var close=true
var q=this.owner.q
if(item.url){
var trgFrame=q.cntFrame
var startPos=item.dispText.indexOf('<!--')
if(startPos!=-1){
var endPos=item.dispText.indexOf('-->',startPos)
trgFrame=item.dispText.substring(startPos+4,endPos)}
if(trgFrame){
if(trgFrame=="_blank")window.open(item.url)
else if(trgFrame=="_top")window.top.location.href=item.url
else if(trgFrame.indexOf('_')==0)parent.location.href=item.url
else{
var fr=findFr(window.top,trgFrame)
if(fr)fr.location.href=item.url
else window.location.href=item.url}}
else{
var find=item.url.indexOf("javascript:")
if(find!=-1){
eval(item.url.substring(find))
if(item.url.indexOf("scroll")!=-1)close=false}
else{
var mt=item.url.indexOf("mailto:")
if(mt!=-1)window.top.location=item.url.substring(mt)
else q.targetFrame.location=item.url}}
if(q.v17&&close)f06(q,q.v17.id,1)}}
function f21(q){
if(q.v29Str){
eval(q.v29Str)
if(q.v29)clearTimeout(q.v29)
q.v29=setTimeout("f21("+q.name+")",q.scrollDelay)}}
function f22(){
var item=this
var q=this.owner.q
var bOp=0
if(item.id&&item.id.indexOf("scroll")!=-1){
q.v29Str=item.url
var jsind=q.v29Str.indexOf('javascript:')
if(jsind!=-1)q.v29Str=q.v29Str.substring(jsind)
f21(q)
return}
if(item.owner.v14){
if(item.v30&&item.v30+'popup'==item.owner.v14.id)bOp=1
if(!bOp)f06(q,item.owner.v14.id)}
if(item.url&&item.url.indexOf("javascript:")==-1)
window.status=item.url
else
window.status=""
f34(item.owner,item)
item.style.color=item.owner.v05
item.style.backgroundColor=item.owner.v07
if(item.v30&&!bOp){
var rect=f19(q,item)
var x=rect.right-q.levelOffset
var y=rect.top
var popup=f05(q,item.v30,item.owner.level+1,item.owner)
item.owner.v14=popup
f08(q,popup,x,y+2,false,item.owner)}}
function f23(){
var item=this
var q=this.owner.q
if(q.v29){q.v29Str=null;clearTimeout(q.v29);}
if(item.id&&item.id.indexOf("scroll")!=-1)return
window.status=""}
function exM(q,popupId,refWnd,dum,ml,mt,mr,mb){
if(!docLoaded)return
if(q.v17Timeout)clearTimeout(q.v17Timeout)
if(q.v17&&q.v17.id!=popupId+"popup")
f06(q,q.v17.id)
if(popupId=='none')return
var rect
if(refWnd=='coords'){
rect=f18(q,zz(0,q.name+'tl'))
rect.left=rect.left+ml
rect.top=rect.top+mt
rect.right=rect.left+mr
rect.bottom=rect.top+mb}
else{
rect=f18(q,zz(0,refWnd))}
if(q.bVarWidth&&!q.v11)q.v02=rect.right-rect.left+(IE4?q.bord*2:0)
var x
var y
x=rect.left-q.bord
y=rect.bottom+q.popupOffset
var popup=f05(q,popupId,0,null)
f08(q,popup,x+q.xOff,y+q.yOff,true,null)
q.v17=popup}
function coM(q,popupId){
if(!docLoaded)return
var popup=zz(q.v18,popupId+"popup")
if(popup)f15Impl(q,popup)}
function exMNS(q,popupId,e,dItem){}
function coMNS(q,popupId){}
function f28(){
var nmn
for(nmn=1;nmn<=lastm;nmn++){
var q=eval("window.m"+nmn)
if(q&&q.v17)f06(q,q.v17.id,1)}}
function f29(){
if(docLoaded)return
var nmn
for(nmn=1;nmn<=lastm;nmn++){
var q=eval("window.m"+nmn)
if(q){
q.v18=(q.v19&&!q.v20)?findFr(window.top,q.v24):window
q.targetFrame=(q.v19)?findFr(window.top,q.cntFrame):window
if(!q.mout)f30(q.v18.document,"mousedown",f28,false)}}
docLoaded=true}
function f30(obj,event,fun,bubble){
if(obj.addEventListener)
obj.addEventListener(event,fun,bubble)
else
eval("obj.on"+event+"="+fun)}
function chgBg(q,item,color,cl){
if(!IE4&&!DOM&&!Opera7)return
var el=zz(0,item)
var ela=zz(0,item+'a')
if(color==0){
if(cl){
if(!q.v25)el.style.background=q.tlmOrigBg
if(ela)ela.style.color=q.tlmOrigCol
el.style.color=q.tlmOrigCol}}
else{
if(q.actm)chgBg(q,q.actm,0,1)
if(!q.v25&&(color&1))el.style.background=q.tlmHlBg
if(ela&&color&2)ela.style.color=q.tlmHlCol
el.style.color=q.tlmHlCol
q.actm=item}}
function f31(){
var i
for(i=0;i<=document.lastLoadHandler;i++){
eval(document.loadHandlers[i]+'();')}}
