//script generated by SiteXpert (www.xtreeme.com/sitexpert/)
//Copyright(C) 1998-2003 Xtreeme GmbH
NS60=(navigator.userAgent.indexOf("Netscape6/6.0")!=-1)
Opera=(navigator.userAgent.indexOf('Opera')!=-1)||(navigator.appName.indexOf('Opera')!=-1)||(window.opera)
Opera7=(Opera&&document.createElement!=null&&document.addEventListener!=null)
IE4=(document.all&&!Opera)
mac=((IE4)&&(navigator.appVersion.indexOf("Mac")!=-1))
DOM=document.documentElement&&!IE4&&!Opera
NS4=navigator.appName.indexOf("Netscape")>-1&&!DOM
mswnd=(navigator.appVersion.indexOf("Windows")!=-1||navigator.appVersion.indexOf("WinNT")!=-1)
if(IE4){
av=navigator.appVersion
avi=av.indexOf("MSIE")
if(avi==-1){version=parseInt(av);}else{version=parseInt(av.substr(avi+4));}}
var ver='6.1.4EnPro'
var m1=new Object
m1.name='m1'
m1.fnm='sitemap_m1'
if(!window.lastm||window.lastm<1)lastm=1
if(NS4||IE4||DOM||Opera){
m1.v17=null
m1.v17Timeout=''
var maxZ=1000
m1.v18
m1.targetFrame
var docLoaded=false
m1.bIncBorder=true
m1.v29=null
m1.v29Str=''
m1.scrollDelay=50
m1.scrollStep=10
m1.showDelayedTimeout=null
m1.fadingSteps=8
m1.v21="/menu"
m1.maxlev=0
m1.v22=0
m1.bVarWidth=0
m1.bShowDel=0
m1.v23=160
m1.levelOffset=20
m1.bord=2
m1.vertSpace=3
m1.sep=0
m1.v19=false
m1.rev=0
m1.shs=0
m1.xOff=0
m1.yOff=0
m1.v20=false
m1.cntFrame=""
m1.menuFrame=""
m1.v24=""
m1.mout=true
m1.iconSize=8
m1.closeDelay=1000
m1.tlmOrigBg="White"
m1.tlmOrigCol="#003063"
m1.v25=true
m1.popupOpacity=0
m1.v11=true
m1.rm=-1
if(document.getElementById&&(!Opera||Opera7))m1.bord=0
m1.v10=8
m1.popupLeftPad=2
m1.v01=2
m1.tlmHlBg=""
m1.tlmHlCol="blue"
m1.borderCol="Black"
m1.menuHorizontal=true
m1.scrollHeight=6}
m1.lev0=new Array("12px",false,false,"#003063","White","blue","Verdana,Arial,Helvetica","White")
absPath=""
if(m1.v19&&!m1.v20){
if(window.location.href.lastIndexOf("\\")>window.location.href.lastIndexOf("/")) {sepCh = "\\" ;} else {sepCh = "/" ;}
absPath=window.location.href.substring(0,window.location.href.lastIndexOf(sepCh)+1)}
m1.popupOffset=1
m1.v02=m1.v23
if(DOM||IE4||Opera7){
document.write("<img width=1 height=1 id='m1menubg4' src='/menu/sitemap_m1bg4.gif' style='display:none' />")
document.write("<img width=1 height=1 id='m1menubg5' src='/menu/sitemap_m1bg5.gif' style='display:none' />")
document.write("<img width=1 height=1 id='m1menubg6' src='/menu/sitemap_m1bg6.gif' style='display:none' />")}
if(Opera&&!Opera7)document.write("<"+"script language='JavaScript1.2' src='/menu/menu_opera.js'><"+"/"+"script>")
else if(NS4)document.write("<"+"script language='JavaScript1.2' src='/menu/menu_ns4.js'><"+"/"+"script>")
else if(document.getElementById)document.write("<"+"script language='JavaScript1.2' src='/menu/menu_dom.js'><"+"/"+"script>")
else document.write("<"+"script language='JavaScript1.2' src='/menu/menu_ie4.js'><"+"/"+"script>")
document.write("<style type='text/css'>\n")
document.write(".m1CL0,.m1CL0:link{text-decoration:none;color:#003063; }\n")
document.write(".m1CL0:visited{color:#003063}\n")
document.write(".topFold{position:"+(!DOM&&!IE4?"relative":"static")+"}\n")
if(NS4&&!m1.v25)document.write(".x1{padding-left:10px;padding-right:10px;}\n")
document.write(".m1mit{"+((!NS4||m1.v25)?"padding-left:10px;padding-right:10px;":"")+"color:#003063; font-family:Verdana,Arial,Helvetica; font-size:12px; }\n")
document.write("</style>\n\n")
